spring:
  datasource:
      url: ${SPRING_DATASOURCE_URL}?prepareThreshold=0
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        generate_statistics: true  # <--- 이게 true로 찍혀야 범인을 잡습니다.
        format_sql: true


app:
  storage:
    path: "/tmp/storage"
  supabase:
    url: https://keqqwlmmmdwoyspihrtx.supabase.co
    api-key: ${SUPABASE_KEY}
    bucket: hr-storage

logging:
  level:
    org.hibernate.orm.jdbc.bind: info # 쿼리에 들어가는 파라미터 확인
    org.hibernate.stat: debug # 쿼리 실행 시간 통계 출력