spring:
  datasource:
      url: ${SPRING_DATASOURCE_URL}?prepareThreshold=0
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false


app:
  storage:
    path: "/tmp/storage"
  supabase:
    url: https://keqqwlmmmdwoyspihrtx.supabase.co
    api-key: ${SUPABASE_KEY}
    bucket: hr-storage