spring:
  profiles:
    active: local # [스위치] 기본값은 로컬로 설정! 배포할 때만 서버에서 이걸 prod로 바꿈

# Swagger 설정은 로컬이나 서버나 똑같이 확인해야 하니 공통에 둠
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

# 백업 주기도 시스템 공통 정책이므로 여기에 위치
backup:
  interval: "0 0 * * * *"