spring:
  # 1. H2 인메모리 DB (내 컴 메모리에서만 돎)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # 2. 로컬 개발 편의 설정
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none # [중요] 우리가 schema.sql을 직접 관리하기로 했으니 none으로!
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # 3. SQL 초기화 (schema.sql, data.sql 읽기 스위치)
  sql:
    init:
      mode: always

  # 4. 로컬 전용 H2 콘솔
  h2:
    console:
      enabled: true
      path: /h2-console

# 5. 내 노트북 전용 저장 경로
app:
  storage:
    path: "./data/storage"
