
CREATE TABLE IF NOT EXISTS departments (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(500),
    employee_count INTEGER NOT NULL DEFAULT 0,
    established_date DATE NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
    );


CREATE TABLE IF NOT EXISTS binary_contents (
                                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               file_name VARCHAR(200) NOT NULL,
    file_size BIGINT NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
    );


CREATE TABLE IF NOT EXISTS employees (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         employee_number VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    position VARCHAR(50),
    status VARCHAR(20) NOT NULL,
    hire_date DATE NOT NULL,
    resignation_date DATE,
    department_id BIGINT,
    profile_image_id BIGINT UNIQUE,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    -- ENUM 제약 조건 추가
    CONSTRAINT CK_EMP_STATUS CHECK (status IN ('ACTIVE', 'ON_LEAVE', 'RESIGNED')),
    CONSTRAINT FK_EMP_DEPT FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT FK_EMP_PROFILE FOREIGN KEY (profile_image_id) REFERENCES binary_contents(id)
    );


CREATE TABLE IF NOT EXISTS change_logs (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           employee_number VARCHAR(100) NOT NULL,
    type VARCHAR(20) NOT NULL,
    memo VARCHAR(255) NOT NULL,
    ip_address VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT CK_LOG_TYPE CHECK (type IN ('CREATED', 'DELETED', 'UPDATED'))
    );


CREATE TABLE IF NOT EXISTS channel_diff (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            change_log_id BIGINT,
                                            property_name VARCHAR(255) NOT NULL,
    before VARCHAR(255) NOT NULL,
    after VARCHAR(255) NOT NULL,
    CONSTRAINT FK_DIFF_LOG FOREIGN KEY (change_log_id) REFERENCES change_logs(id)
    );


CREATE TABLE IF NOT EXISTS backup_history (
                                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              worker VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL,
    file_id BIGINT,
    started_at TIMESTAMP(6) NOT NULL,
    ended_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT CK_BACKUP_STATUS CHECK (status IN ('COMPLETED', 'FAILED', 'IN_PROGRESS', 'SKIPPED'))
    );